### ISSUE TITLE
Replace jbuilder

### ISSUE THREAD

**Issue by MaicolBen** [rootstrap/rails_api_base#128]
Check [jb](https://github.com/amatsuda/jb), it's considered faster than jbuilder

Another alternative faster and cleaner is [fast_jsonapi](https://github.com/Netflix/fast_jsonapi) which is based on serializers, so it's like having views + decorators in the same file.

Feel free to close this issue if none of these gems is a good replacement.

**Comment by juanmanuelramallo** [comment]
Moving this issue forward, what do you think about using json:api as the standard for our API responses? 

Among several implementations, fast_josnapi has been widely accepted by the community. 
Active Model Serializers is the rails' generic implementation of serializers, with the json:api adapter they provide support for this standard though it's time-benchmarked poorly.

Take into account that this change is not only about improving our response times, but also to provide a standard way to respond in our API endpoints.

**Comment by megatux** [comment]
the gem fast_jsonapi from Netflix is no [longer maintained](https://github.com/Netflix/fast_jsonapi#since-this-project-is-no-longer-maintained-please-consider-using-alternatives-or-the-forked-project-jsonapi-serializerjsonapi-serializer). The recommended active [fork is here](https://github.com/jsonapi-serializer/jsonapi-serializer).

**Comment by santib** [comment]
Closing this one since `jbuilder` is "official" under the `rails` org. Unless there is a convincing reason to change it, I'd suggest sticking with it.
