### ISSUE TITLE
Arctic_admin missing icons

### ISSUE THREAD

**Issue by CR1AT0RS** [rootstrap/rails_api_base#260]
## Bug report:
* **Expected Behavior**: 
Arctic_admin icons show up
* **Actual Behavior**: 
Arctic_admin icons missing

Original issue: https://github.com/cprodhomme/arctic_admin/issues/39 
Fontawesome dependecy required

**Comment by CR1AT0RS** [comment]
pull request: #261

**Comment by sjieg** [comment]
Good stuff @CR1AT0RS I was just looking for this.

For reference while other people finding this ticket:
While I was implementing your solution, I tried to use our pro license:
```
import "@fortawesome/fontawesome-pro/css/all.css";
```
But this does not work, because `font-family: 'Font Awesome Free 5';` is directly defined in the css. I've reported a suggested feature to support this as well: #262 

For now I'll just have to have both pro and free installed in my node_modules.
